store/products/urls.py
from django.contrib import admin
from django.urls import path
from products.views import ProductView, basket_add, ProductsList, ProductsCategoryList

urlpatterns = [
    path("<int:product_id>/", ProductView.as_view(), name="product-detail"),
    path("baskets/add/<int:product_id>/", basket_add, name="basket_add"),
    path("all-prods/", ProductsList.as_view(), name="all-prods"),
    path("cat/<slug:category_slug>", ProductsCategoryList.as_view(), name="category"),
]

store/store/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('products/', include(('products.urls', 'products'), namespace='products')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/products/models.py
from django.core.exceptions import ValidationError
from django.db import models
from django.contrib.auth.models import AbstractUser
from datetime import datetime as dt

from django.urls import reverse
from users.models import User


class Color(models.Model):
    name = models.CharField(max_length=255, unique=True)

    class Meta:
        verbose_name = 'Цвет'
        verbose_name_plural = 'Цвета'

    def __str__(self):
        return self.name


class Size(models.Model):
    name = models.CharField(max_length=255, unique=True)

    class Meta:
        verbose_name = 'Размер'
        verbose_name_plural = 'Размеры'

    def __str__(self):
        return self.name


class Sex(models.Model):
    name = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Пол'
        verbose_name_plural = 'Пол'


class TypeOfProduct(models.Model):
    name = models.CharField(max_length=255, unique=True)

    def get_categories(self):
        return ProductCategory.objects.filter(type=self)

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Тип товара'
        verbose_name_plural = 'Типы товаров'


class ProductCategory(models.Model):
    name = models.CharField(max_length=255, unique=True)
    type = models.ForeignKey(to=TypeOfProduct, on_delete=models.CASCADE)
    description = models.TextField(null=True, blank=True)
    slug = models.SlugField(max_length=255, unique=True, db_index=True, verbose_name='URL')

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    price = models.DecimalField(max_digits=255, decimal_places=2)
    quantity = models.PositiveIntegerField(default=0)
    category = models.ForeignKey(to=ProductCategory, on_delete=models.CASCADE)
    sex = models.ForeignKey(to=Sex, on_delete=models.CASCADE, blank=True)
    size = models.ManyToManyField(to=Size)
    color = models.ManyToManyField(to=Color)

    def get_absolute_url(self):
        return reverse('products:product-detail', kwargs={'product_id': self.id})

    def get_type(self):
        category_id = self.category.id
        type = ProductCategory.objects.get(id=category_id).type
        return ProductCategory.objects.filter(type=type)

    def get_img(self):
        return ProductImages.objects.filter(product_id=self.id)[0]

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'

    def __str__(self):
        return f'Товар: {self.name} | Категория: {self.category.name}'



class ProductImages(models.Model):
    product = models.ForeignKey(to=Product, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='products_images')

    def count_images(self):
        count = ProductImages.objects.filter(product_id=self.product.id).count()
        if count >= 5:
            raise ValidationError(f'Можно добавить не более 5 изображений')

    def save(self, *args, **kwargs):
        self.count_images()
        super(ProductImages, self).save(*args, **kwargs)

    class Meta:
        verbose_name = 'Картинка товара'
        verbose_name_plural = 'Картинки товара'

    def __str__(self):
        return f'Картинка для {self.product.name}'


class ReviewsQuerySet(models.QuerySet):

    def avarage_points(self):
        if len(self) > 0:
            return sum(review.points for review in self) / self.count()
        else:
            return 0


class Review(models.Model):
    user = models.ForeignKey(to=User, on_delete=models.CASCADE)
    points = models.SmallIntegerField()
    description = models.TextField(null=True, blank=True)
    product = models.ForeignKey(to=Product, on_delete=models.CASCADE)
    created_timestamp = models.DateTimeField(auto_now_add=True)

    objects = ReviewsQuerySet.as_manager()

    def date_create(self):
        date = self.created_timestamp
        return date.strftime('%d.%m.%Y')


    class Meta:
        verbose_name = 'Отзыв товара'
        verbose_name_plural = 'Отзывы товара'

    def __str__(self):
        return f'Отзыв для товара: {self.product.name} | Оценка: {self.points}'


class BasketQuerySet(models.QuerySet):

    def total_sum(self):
        return sum(basket.sum() for basket in self)

    def total_quantity(self):
        return sum(basket.quantity for basket in self)


class Basket(models.Model):
    user = models.ForeignKey(to=User, on_delete=models.CASCADE)
    product = models.ForeignKey(to=Product, on_delete=models.CASCADE)
    quantity = models.PositiveSmallIntegerField(default=0)
    created_timestamp = models.DateTimeField(auto_now_add=True)

    objects = BasketQuerySet.as_manager()

    class Meta:
        verbose_name = 'Корзина'
        verbose_name_plural = 'Корзина'

    def __str__(self):
        return f'Корзина для {self.user.email} | Продукт: {self.product.name}'

    def sum(self):
        return self.product.price * self.quantity

store/products/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.core.paginator import Paginator

from .models import Product, ProductImages, Review, Basket, ProductCategory
from .utils import DataMixin


class ProductView(DataMixin, DetailView):
    model = Product
    template_name = 'products/single_product_variable.html'
    pk_url_kwarg = 'product_id'
    context_object_name = 'product'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['colors'] = context['product'].color.all()
        context['sizes'] = context['product'].size.all()
        context['images'] = ProductImages.objects.filter(product_id=context['product'].id)
        context['reviews'] = Review.objects.filter(product_id=context['product'].id)
        context['reviews_count'] = context['reviews'].count()
        context['avarage_points'] = context['reviews'].avarage_points()
        context['related_cats'] = context['product'].get_type()
        context['baskets'] = Basket.objects.filter(user=self.request.user)
        context['related_prods'] = []
        for cat in context['related_cats']:
            context['related_prods'] += Product.objects.filter(category_id=cat.id)
        c_def = self.get_user_context()
        return dict(list(context.items()) + list(c_def.items()))


def basket_add(request, product_id):
    product = Product.objects.get(id=product_id)
    basket = Basket.objects.filter(user=request.user, product=product)

    if not basket.exists():
        Basket.objects.create(user=request.user, product=product, quantity=1)
    else:
        basket = basket.first()
        basket.quantity += 1
        basket.save()

    return HttpResponseRedirect(request.META['HTTP_REFERER'])


class ProductsList(DataMixin, ListView):
    model = Product
    paginate_by = 30
    context_object_name = 'products'
    template_name = 'products/home_clean.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context()
        return dict(list(context.items()) + list(c_def.items()))


class ProductsCategoryList(DataMixin, ListView):
    model = Product
    paginate_by = 30
    slug_url_kwarg = 'category_slug'
    context_object_name = 'products'
    template_name = 'products/home_clean.html'

    def get_queryset(self):
        return Product.objects.filter(category__slug=self.kwargs['category_slug'])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context()
        return dict(list(context.items()) + list(c_def.items()))

store/products/templates/products/base.html
{% load static %}

<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
    <title>{{ title }}</title>
    <link rel="stylesheet" href='{% static "css/owl.carousel.min.css" %}'>
    <link rel="shortcut icon" href='{% static "img/favicon.png" type="image/png" %}'>
    <link rel="stylesheet" type='{% static "text/css" href="css/bootstrap-slider.css" %}'>
    <link rel="stylesheet" href='{% static "css/slick.css" %}'>
    <link rel="stylesheet" href='{% static "css/slick-theme.css" %}'>
    <link rel="stylesheet" type="text/css" href='{% static "css/style.css" %}'>
    <link rel="stylesheet" href='{% static "css/my_css.css" %}'>
<!--    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">-->
    {% block css %}{% endblock %}
</head>

<body>
    <!--push menu cart -->
    {% include 'products/basket.html' %}
    <!-- End cart -->
    <div class="modal fade" id="myModal" role="dialog">
        <div class="modal-dialog">
            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">SEARCH HERE</h4>
                </div>
                <div class="modal-body">
                    <div class="input-group">
                        <form method="get" class="searchform" action="/search" role="search">
                            <input type="hidden" name="type" value="product">
                            <input type="text" name="q" class="form-control control-search">
                            <span class="input-group-btn">
                              <button class="btn btn-default button_search" type="button"><i data-toggle="dropdown" class="fa fa-search"></i></button>
                            </span>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--END  Modal content-->
    <div class="wrappage">
        <header id="header" class="header-v4 header-top-absolute home-clean">
<!--            <div class="sticky-header border-grey-bottom text-center hidden-xs hidden-sm">-->
<!--                <div class="text">-->
<!--                    <span class="u-line">Free shipping and returns</span> on all orders above $200-->
<!--                </div>-->
<!--            </div>-->
            <div class="topbar">
                <div class="container container-40">
                    <div class="topbar-left">
                        <div class="topbar-option">
                            <div class="topbar-account">
                                <a href="#"><i class="icon-user f-15"></i></a>
                            </div>
                            <div class="topbar-wishlist">
                                <a href="#">
                                <i class="icon-heart f-15"></i>
                                <span class="count wishlist-count">0</span>
                            </a>
                            </div>
                            <ul class="menu">
                                {% for p in menu %}
                                <li>
                                    <a href="#">{{ p.name }}</a>
                                    <ul class="dropdown">
                                        {% for l in p.get_categories %}
                                            <li><a class="" href="{% url 'products:category' l.slug %}">{{ l.name }}</a></li>
                                        {% endfor %}
                                    </ul>
                                </li>
                                {% endfor %}
                            </ul>
<!--                            {% for p in menu %}-->
<!--                                <div class="menu-p"><p>{{ p.name }}</p></div>-->
<!--                                <div class="drr">-->
<!--                                    <ul class="menu-list" aria-labelledby="">-->
<!--                                        {% for l in p.get_categories %}-->
<!--                                            <li><a class="" href="#">{{ l.name }}</a></li>-->
<!--                                        {% endfor %}-->
<!--                                    </ul>-->
<!--                                </div>-->
<!--                            {% endfor %}-->
                        </div>
                        <!--end topbar-option-->
                    </div>
                    <!--end topbar-left-->

                    <div class="topbar-center">
                        <div class="logo">
                            <img src="{% static 'img/logo.jpg' %}">
                        </div>
                    </div>

                    <div class="topbar-right">
                        <div class="topbar-option">
                            <div class="topbar-search">
                                <div class="search-popup dropdown" data-toggle="modal" data-target="#myModal">
                                    <a href="#"><i class="icon-magnifier f-15"></i></a>
                                </div>
                            </div>
                            <div class="topbar-cart">
                                <a href="#" class="icon-cart">
                                <i class="icon-basket f-15"></i>
                                <span class="count cart-count">0</span>
                            </a>
                            </div>
                        </div>
                        <!--end topbar-option-->
                    </div>
                    <!--end topbar-right-->
                    <div class="clearfix"></div>
                </div>
            </div>
        </header>
        {% block content %}{% endblock %}
        <footer>
            <div class="container container-42">
                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-6 col-lg-4">
                        <div class="menu-footer">
                            <ul>
                                <li><a href="#">Shipping</a></li>
                                <li><a href="#">Terms & Conditions</a></li>
                                <li><a href="#">Privacy Policy</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-6 col-lg-4">
                        <div class="newletter-form">
                            <h3 class="footer-title text-center">Newsletter</h3>
                            <form action="#">
                                <input type="text" name="s" placeholder="Email Adress..." class="form-control">
                                <button type="submit" class="btn btn-submit">
                                    <i class="fa fa-angle-right"></i>
                                </button>
                            </form>
                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-4">
                        <div class="social">
                            <a href="#" title="twitter">
                            <i class="fa fa-twitter"></i>
                        </a>
                            <a href="#" title="facebook">
                            <i class="fa fa-facebook"></i>
                        </a>
                            <a href="#" title="google plus">
                            <i class="fa fa-google-plus"></i>
                        </a>
                            <a href="#" title="Pinterest">
                            <i class="fa fa-pinterest-p"></i>
                        </a>
                            <a href="#" title="rss">
                            <i class="fa fa-rss"></i>
                        </a>
                        </div>
                    </div>
                </div>
            </div>
        </footer>
    </div>
    <a href="#" class="scroll_top">SCROLL TO TOP<span></span></a>
    <script src='{% static "js/jquery.js" %}'></script>
    <script src='{% static "js/bootstrap.js" %}'></script>
    <script src='{% static "js/owl.carousel.min.js" %}'></script>
    <script src='{% static "js/slick.min.js" %}'></script>
    <script src='{% static "js/masonry.pkgd.min.js" %}'></script>
    <script src='{% static "js/main.js" %}'></script>
<!--    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>-->
</body>
</html>

store/products/templates/products/single_product_variable.html
{% extends 'products/base.html' %}
{% load static %}


    {% block content %}
        <div class="container container-42">
            <ul class="breadcrumb">
                <li><a href="#">Home</a></li>
                <li><a href="#">{{ product.sex }}</a></li>
                <li class="active"><a href="#">{{ product.name }}</a></li>
            </ul>
        </div>
        <div class="container">
            <div class="single-product-detail product-bundle">
                <div class="row">
                    <div class="col-xs-12 col-sm-5 col-md-6">
                        <div class="product-images">
                            <div class="main-img js-product-slider">
                                {% for image in images %}
                                    <a href="#" class="hover-images effect"><img src='{{ image.image.url }}' alt="photo" class="img-reponsive"></a>
                                {% endfor %}
                            </div>
                        </div>
                        <div class="multiple-img-list-ver2 js-click-product">
                            {% for image in images %}
                                <div class="product-col">
                                    <div class="img">
                                        <img src='{{ image.image.url }}' alt="images" class="img-responsive">
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-7 col-md-6">
                        <div class="single-product-info">
                            <div class="rating-star">
                                <div class="icon-rating"><span class="star-5"></span>
                                    {% if avarage_points >= 5 %}
                                            <span class="star star-5"></span>
                                        {% endif %}
                                        {% if avarage_points >= 4 %}
                                            <span class="star star-4"></span>
                                        {% endif %}
                                        {% if avarage_points >= 3 %}
                                            <span class="star star-3"></span>
                                        {% endif %}
                                        {% if avarage_points >= 2 %}
                                            <span class="star star-2"></span>
                                        {% endif %}
                                        {% if avarage_points >= 1 %}
                                            <span class="star star-1"></span>
                                        {% endif %}
                                </div>
                                <span class="review">({{ reviews_count }} customer review)</span>
                            </div>
                            <h3 class="product-title space-pm"><a href="#">{{ product.name }}</a></h3>
                            <div class="product-price">
                                <span>₽{{ product.price }}</span>
                            </div>
<!--                            <p class="product-desc">{{ product.description }}</p>-->
                            <div class="form-group">
                                <label for="color">Color</label>
                                <select class="form-control" id="color">
                                    <option>Choose an option</option>
                                    {% for color in colors %}
                                        <option>{{ color.name }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="size">Size</label>
                                <select class="form-control" id="size">
                                    <option>Choose an option</option>
                                    {% for size in sizes %}
                                        <option>{{ size.name }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                            <div class="action">
<!--                                <div class="quantity">-->
<!--                                    <button type="button" class="quantity-left-minus btn btn-number js-minus" data-type="minus" data-field="">-->
<!--                                        <span class="minus-icon">-</span>-->
<!--                                    </button>-->
<!--                                    <input type="text" name="number" value="1" class="product_quantity_number js-number">-->
<!--                                    <button type="button" class="quantity-right-plus btn btn-number js-plus" data-type="plus" data-field="">-->
<!--                                        <span class="plus-icon">+</span>-->
<!--                                    </button>-->
<!--                                </div>-->
                                <a href="{% url 'products:basket_add' product.id %}" class="link-ver1 add-cart add-right">Add To Cart</a>
                                <a href="#" class="link-ver1 wish center-heart"><i class="icon-heart f-15"></i></a>
                                <div class="clearfix"></div>
                            </div>
                            <div class="share-social">
                                <span>Share :</span>
                                <a href="#"><i class="fa fa-twitter cenn"></i></a>
                                <a href="#"><i class="fa fa-facebook cenn"></i></a>
                                <a href="#"><i class="fa fa-google-plus cenn"></i></a>
                                <a href="#"><i class="fa fa-pinterest-p cenn"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!--single-product-detail-->
        </div>
        <div class="container container-fullwidth">
            <div class="single-product-tab ver2">
                <ul class="nav nav-tabs text-center">
                    <li class="active"><a data-toggle="pill" href="#info">Description</a></li>
                    <li><a data-toggle="pill" href="#review">Reviews ({{ reviews_count }})</a></li>
                </ul>
                <div class="tab-content">
                    <div id="info" class="tab-pane fade in active">
                        <p class="p-center space-padding-tb-30">{{ product.description }}</p>
                    </div>
                    <div id="review" class="tab-pane fade in ">
                        <div class="all-reviews">
                            {% for review in reviews %}
                                <div class="review">
                                    <div class="review-wrapper">
                                        <p>{{ review.user }}</p>
                                        <div class="icon-rating"><span class="star-5"></span>
                                            {% if review.points >= 5 %}
                                                <span class="star star-5"></span>
                                            {% endif %}
                                            {% if review.points >= 4 %}
                                                <span class="star star-4"></span>
                                            {% endif %}
                                            {% if review.points >= 3 %}
                                                <span class="star star-3"></span>
                                            {% endif %}
                                            {% if review.points >= 2 %}
                                                <span class="star star-2"></span>
                                            {% endif %}
                                            {% if review.points >= 1 %}
                                                <span class="star star-1"></span>
                                            {% endif %}
                                        </div>
                                        <p>{{ review.date_create }}</p>
                                    </div>

                                    <p>{{ review.description }}</p>

                                </div>
    <!--                            <p class="p-center space-padding-tb-30">{{ review.user }}</p>-->
    <!--                            <p class="p-center space-padding-tb-30">{{ review.description }}</p>-->
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!--single-product-tab-->
        <div class="information">
            <ul>
                <li class="info-center text-center"><span>SKU :</span>
                    <a href="">004004</a>
                </li>
                <li class="info-center bd-rl text-center"><span>Categories :</span>
                    <a href="">{{ product.category.name }}</a>
                </li>
                <li class="info-center text-center"><span>Tags :</span>
                    <a href="">Designer</a>,
                    <a href="">Tech</a>
                </li>
            </ul>
        </div>
        <div class="product-related">
            <div class="container container-42">
                <h3 class="title text-center">Related Products</h3>
                <div class="owl-carousel owl-theme js-owl-product">
                    {% for rel in related_prods %}
                        <div class="product-item">
                            <div class="product-images">
                                <a href="{{ rel.get_absolute_url }}" class="hover-images effect"><img src='{{ rel.get_img.image.url }}' alt="products" class="img-reponsive"></a>
                                <a href="#" class="btn-add-wishlist ver2"><i class="icon-heart"></i></a>
                                <a href="{{ rel.get_absolute_url }}" class="btn-quickview">QUICK VIEW</a>
                            </div>
                            <div class="product-info-ver2">
                                <h3 class="product-title space-pm"><a href="{{ rel.get_absolute_url }}">{{ rel.name }}</a></h3>
                                <div class="product-after-switch">
                                    <div class="product-price">₽{{ rel.price }}</div>
                                    <div class="product-after-button">
                                        <a href="{% url 'products:basket_add' rel.id %}" class="addcart">ADD TO CART</a>
                                    </div>
                                </div>
                                <div class="rating-star">
                                    {% if review.points >= 5 %}
                                        <span class="star star-5"></span>
                                    {% endif %}
                                    {% if review.points >= 4 %}
                                        <span class="star star-4"></span>
                                    {% endif %}
                                    {% if review.points >= 3 %}
                                        <span class="star star-3"></span>
                                    {% endif %}
                                    {% if review.points >= 2 %}
                                        <span class="star star-2"></span>
                                    {% endif %}
                                    {% if review.points >= 1 %}
                                        <span class="star star-1"></span>
                                    {% endif %}
                                </div>
                                <div class="product-price">₽{{ rel.price }}</div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    {% endblock %}